# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='components',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expose',
        ),
        migrations.AlterUniqueTogether(
            name='componentlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='componentlink',
            name='application',
        ),
        migrations.RemoveField(
            model_name='componentlink',
            name='from_component',
        ),
        migrations.RemoveField(
            model_name='componentlink',
            name='to_service',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='add_to',
            field=models.SlugField(db_index=False, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='target_all_in',
            field=models.SlugField(db_index=False, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='target_any_of',
            field=models.SlugField(db_index=False, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ComponentLink',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
