#!/usr/bin/env python3
# Copyright (c) 2017, Composure.ai
# Copyright (c) 2018, Andrea Corbellini
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the Perfect Storm Project.

import argparse
import logging
import os
import socket
import sys

import tornado.httpserver
import tornado.ioloop
import tornado.log
import tornado.wsgi


def address(addr):
    if ':' not in addr:
        host, port = addr, None
    else:
        host, port = addr.rsplit(':', 1)

        if ']' in port:
            # This is actually an IPv6 address.
            host, port = addr, None
        elif not port:
            # Port is empty, use the default.
            port = None
        else:
            port = int(port)

    if not host:
        raise ValueError(addr)

    return host, port


def parse_env_var(type, envvar, default):
    if os.environ.get(envvar):
        return type(os.environ[envvar])
    else:
        return default


def parse_args():
    parser = argparse.ArgumentParser(
        usage='%(prog)s [OPTIONS]',
        description='Perfect Storm Core API Server')

    parser.add_argument(
        '-b', '--bind', metavar='HOST[:PORT]', type=address, default=[], action='append',
        help='Address to bind. This can be an IPv4 address, and IPv6 address or a host name. The address can '
             'optionally include a port number. If no port is specified, the port specified with -p/--port is '
             'used, or the default port if -p/--port is not provided. This option can be specified multiple '
             'times to bind multiple addresses. Default: 127.0.0.1')
    parser.add_argument(
        '-p', '--port', metavar='PORT', type=int, default=8000, dest='default_port',
        help='Port to bind. See also -b/--bind. Default: 8000')
    parser.add_argument(
        '--mongo', metavar='HOST[:PORT]', type=address, default=None,
        help='MongoDB address. If port is not specified, the default port 27017 is used. Default: 127.0.0.1')

    parser.add_argument(
        '--no-tasks', action='store_false', dest='run_tasks',
        help='Disable running of background tasks')

    parser.add_argument(
        '-D', '--debug', action='store_true',
        help='Enable debug mode')

    options = parser.parse_args()

    if not options.debug:
        options.debug = parse_env_var(bool, 'STORM_DEBUG', False)

    if not options.bind:
        options.bind.append(parse_env_var(address, 'STORM_BIND', ('127.0.0.1', None)))

    if not options.mongo:
        options.mongo = parse_env_var(address, 'STORM_MONGO', ('127.0.0.1', None))
    if not options.mongo[1]:
        options.mongo = (options.mongo[0], 27017)

    return options


def setup_logging():
    formatter = tornado.log.LogFormatter(
        fmt='[%(asctime)s] %(color)s%(message)s%(end_color)s',
        datefmt='%Y-%m-%d %H:%M:%S')

    handler = logging.StreamHandler(stream=sys.stdout)
    handler.setFormatter(formatter)

    logger = logging.getLogger('tornado')
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)


def run():
    options = parse_args()

    os.environ['DJANGO_SETTINGS_MODULE'] = 'teacup.settings'
    os.environ['STORM_DEBUG'] = '1' if options.debug else ''
    os.environ['STORM_MONGODB'] = 'mongodb://{}:{}/perfectstorm'.format(*options.mongo)

    setup_logging()

    from teacup.apiserver import tasks
    from teacup.wsgi import application

    container = tornado.wsgi.WSGIContainer(application)
    http_server = tornado.httpserver.HTTPServer(container)

    for host, port in options.bind:
        if port is None:
            port = options.default_port
        if host and host[0] == '[' and host[-1] == ']':
            bind_host = host[1:-1]
        else:
            bind_host = host

        try:
            http_server.bind(port, bind_host)
        except socket.error as exc:
            print('Failed to bind {}:{}: {}'.format(host, port, exc.args[1]), file=sys.stderr)
            sys.exit(1)

        print('Listening on http://{}:{}/'.format(host, port), file=sys.stderr, flush=True)

    if options.run_tasks:
        tasks.run_tasks()

    try:
        http_server.start(0)
    except KeyboardInterrupt:
        # This code is executed in the main process.
        http_server.stop()
        tasks.stop_tasks()
    else:
        # This code is executed in the forked sub-processes.
        ioloop = tornado.ioloop.IOLoop.current()
        try:
            ioloop.start()
        except KeyboardInterrupt:
            ioloop.stop()


if __name__ == '__main__':
    run()
