#!/usr/bin/env python3
# Copyright (c) 2017, Composure.ai
# Copyright (c) 2018, Andrea Corbellini
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the Perfect Storm Project.

import re
import shlex
import subprocess

import yaml

from perfectstorm.clients import APIClient
from perfectstorm.executors import RecipeExecutor


_var_re = re.compile(r'(?<!\$)\$(\w+|{[^}]*})')


class DockerCommand:

    def __init__(self, args):
        err = False

        if isinstance(args, str):
            var = None
            args = shlex.split(args)
        elif isinstance(args, list):
            var = None
        elif isinstance(args, dict):
            if len(args) == 1:
                var, args = args.popitem()
            else:
                err = True
        else:
            err = True

        if not err:
            if var is not None and not isinstance(var, str):
                err = True
            if not all(isinstance(arg, str) for arg in args):
                err = True

        if err:
            raise TypeError('args must be a string, a list of strings or a dictionary containing a single item')

        if len(args) < 1:
            raise ValueError('Empty command')

        self.var = var
        self.cmd = args[0]
        self.args = args[1:]

    def expand_args(self, environ):
        expanded_args = []

        for arg in self.args:
            expanded = ''

            while arg:
                match = _var_re.search(arg)
                if match is None:
                    expanded += arg
                    break
                start, end = match.span()
                expanded += arg[:start]
                var = match.group(1)
                if var[0] == '{':
                    var = var[1:-1]
                expanded += environ.get(var, '')
                arg = arg[end+1:]

            expanded_args.append(expanded)

        return expanded_args

    def run(self, environ=None):
        if environ is None:
            environ = {}

        args = ['docker', self.cmd] + self.expand_args(self.args)
        process = subprocess.run(args, input=b'', check=True, stdout=subprocess.PIPE)
        output = process.stdout.decode().strip()

        if self.var is not None:
            environ[self.var] = output

        return output


class DockerRecipeExecutor(RecipeExecutor):

    agent_type = 'docker-deployer'

    def before_run(self):
        super().before_run()

        cmd = DockerCommand(['info'])
        info = cmd.run()

        docker_id = None
        for line in info.splitlines():
            if line.startswith('ID: '):
                docker_id = line[4:]

        if docker_id is None:
            raise RuntimeError('Could not find Docker daemon ID')

        self.docker_id = docker_id

    def get_pending_triggers(self):
        qs = super().get_pending_triggers()
        qs.filter(target=self.docker_id)
        return qs

    def get_recipe(self):
        recipe = super().get_recipe()
        commands = yaml.safe_load(recipe.content)
        if not isinstance(commands, list):
            raise TypeError('Recipe content is expected to be a list of commands')
        self.commands = [DockerCommand(item) for item in commands]
        return recipe

    def run_recipe(self, recipe):
        environ = dict(recipe.params)
        for command in self.commands:
            command.run(environ)


class DockerDeployerClient(APIClient):

    def run(self):
        executor = DockerRecipeExecutor()
        executor.run()


if __name__ == '__main__':
    DockerDeployerClient().main()
